spring.application.name=Aula7
server.port=8089

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=false

# JWT
jwt.secret=CHAVE_SUPER_SECRETA_123456789

# Segurança
server.error.include-stacktrace=never

# Configurações de Conexão
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configurações de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true